### ISSUE TITLE
Revert filter options change?

### ISSUE THREAD

**Issue by albfernandez** [albfernandez/struts1#35]
@YSavanier

https://github.com/albfernandez/struts1/pull/32#issuecomment-1032562089

Hello,

sorry but I'm a little confused at what this commit is trying to achieve as now in version 1.3.10-ayg-06 our html:option elements just print html entities as text...

Example (beware, zerowidth space added after & to prevent github interpreting html entities) :

<html:select property="test"><html:option value=""> &​nbsp;V&​eacute;hicule</html:option></html:select>

will render the &​nbsp; and &​eacute; as text !

As html entites are an ensential part of labeling, they should be left untouched by your filtering, so I think it is an unwanted regression. Could you please reconsider this merge or fix it so it leaves the html entities alone please ?

Thank you very much.

B.R.

Y. Savanier

**Comment by albfernandez** [comment]
I think the safe way is to check the filter attribute, if set to true filter both value and text, else filter none of them

```java
if (filter) {
        results.append(TagUtils.getInstance().filter(text()));
}
else {
      	results.append(text());
}
```

**Comment by albfernandez** [comment]
Fixed in 1b0cc5ee4b86dc25c42517fb297c3b6719fcbce1

**Comment by YSavanier** [comment]
Nice, thank you very much !

**Comment by albfernandez** [comment]
You have to escape & for the javascript code inside html:
Example:
[https://erlend.oftedal.no/blog/static-124.html](https://erlend.oftedal.no/blog/static-124.html)

**Comment by albfernandez** [comment]
I've just released a version with the change.
