### ISSUE TITLE
CDI plugin for this Struts 1.x fork

### ISSUE THREAD

**Issue by knextsunj** [albfernandez/struts1#7]
I have updated the my fork of the following CDI plugin for struts 1.x to use releases from your repository and CDI 1.1 for Java EE 7:
https://github.com/reegnz/struts-cdi

My fork is :  https://github.com/knextsunj/struts1-cdi

I am working on a Java EE 7 Web Profile application with your latest struts 1.3.x release. I have not tested this plugin extensively as my app is still in development, but feedback on its current state is always welcome.

The purpose of this issue is to inform you on this plugin. I will post an update on how this plugin is working with your latest release.

Thanks for continuing to publish Struts 1.x and JBoss Seam releases.

**Comment by albfernandez** [comment]
Hi, I've just release to maven. 
There is a version number increment but it's only changes in pom.xml in order to deploy to maven.
I hope you find it useful

```xml
	<dependency>
		<groupId>com.github.albfernandez.struts</groupId>
		<artifactId>struts-core</artifactId>
		<version>1.3.10-ayg-04</version>
	</dependency>
<!-- other modules-->
```
